services:
  - type: web
    name: savings-tracker
    env: python
    pythonVersion: 3.10.12
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && gunicorn savetracker.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
